name: burger-builder

on:
  push:
    paths:
      - "react-the-complete-guide/burger-builder/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: react-the-complete-guide/burger-builder - npm install, build, and test
        working-directory: ./react-the-complete-guide/burger-builder
        run: |
          npm ci
          npm run build --if-present
          npm test -- --watchAll=false
        env:
          CI: true
